config/routes.rb
Rails.application.routes.draw do

  get "movie/:id/mail" => "movies#mail", :as => 'mail_movie'
  get "movie/:id/spam" => "movies#spam", :as => 'spam_movie'
  get 'rental/index'

  get 'rental/show/:id' => "rental#show", :as => 'rental_show'

  devise_for :users
  resources :movies do
    get 'page/:page', :action => :index, :on => :collection
    resources :comments
  end

  get 'people/index'

  get 'home' => "page#home"

  get 'about_us' => "page#about_us"

  post 'contact_us' => "page#contact_us"
  get 'contact_us' => "page#contact_us"

  get 'newsletter' => "page#newsletter"

  get 'blog' => "page#blog"

  get 'page/calendar(/:year(/:month))' => "page#calendar", :as => 'calendar'

  get 'articles' => "page#articles"

  get 'login' => "page#login"

  get 'dave/teach'

  get 'dave/speak'

  get 'dave/dig'

  get 'say/dave' => 'say#hello'
  get 'say/goodbye'
  get 'say/something'

   root 'page#home'

end

app/controllers/rental_controller.rb
class RentalController < ApplicationController
  def index
    @movies = Movie.page(2).order(:updated_at => :desc)
  end

  def show
    @movie = Movie.find( params['id'])
  end
end

app/helpers/rental_helper.rb
module RentalHelper
end

app/views/rental/index.html.erb
<p id="notice"><%= notice %></p>
<% if is_admin? %>
    <h2>ADMIN:</h2>
    <%= link_to "Movies Admin", movies_path %>
<% end %>

<h1>Listing Movies</h1>
<%#= link_to "Previous", movies_path(:page => @previous_page )%> &nbsp
<%#= link_to "Next", movies_path(:page => @next_page )%>
<%= paginate @movies %>

<table>
  <thead>
  <tr>
    <th>ID</th>
    <th>Name</th>
    <th>Director</th>
    <th>Description</th>
    <th>Year</th>
    <th>Length</th>
    <th>Format</th>
    <th>Thumbnail</th>
    <th></th>
  </tr>
  </thead>

  <tbody>
  <% @movies.each do |movie| %>
      <tr>
        <td><%= link_to movie.proper_name, rental_show_path(movie.id) %></td>
        <td><%= movie.director %></td>
        <td><%= truncate(movie.description, length: 20 )%></td>
        <td><%= movie.year %></td>
        <td><%= movie.length %></td>
        <td><%= movie.format %></td>
        <td><%= link_to( image_tag(movie.thumbnail), movie) %></td>
        <td><%= link_to 'Show', rental_show_path( movie.id ) %></td>

      </tr>
  <% end %>
  </tbody>
</table>

app/views/rental/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @movie.proper_name %>
</p>

<p>
  <strong>Director:</strong>
  <%= @movie.director %>
</p>

<p>
  <strong>Description:</strong>
  <%= @movie.description.html_safe %>
</p>

<p>
  <strong>Year:</strong>
  <%= @movie.year %>
</p>

<p>
  <strong>Length:</strong>
  <%= @movie.length %>
</p>

<p>
  <strong>Format:</strong>
  <%= @movie.format %>
</p>

<p>
  <strong>Image:</strong>
  <%= image_tag @movie.image %>
</p>
<p>
  <strong>Thumbnail Image:</strong>
  <%= image_tag @movie.image %>
</p>


<%= link_to 'Back', rental_index_path %>