config/routes.rb
Rails.application.routes.draw do

  get "movie/:id/mail" => "movies#mail", :as => 'mail_movie'
  get "movie/:id/spam" => "movies#spam", :as => 'spam_movie'
  get 'rental/index'

  get 'rental/show/:id' => "rental#show", :as => 'rental_show'

  devise_for :users
  resources :movies do
    get 'page/:page', :action => :index, :on => :collection
    resources :comments
  end

  get 'people/index'

  get 'home' => "page#home"

  get 'about_us' => "page#about_us"

  post 'contact_us' => "page#contact_us"
  get 'contact_us' => "page#contact_us"

  get 'newsletter' => "page#newsletter"

  get 'blog' => "page#blog"

  get 'page/calendar(/:year(/:month))' => "page#calendar", :as => 'calendar'

  get 'articles' => "page#articles"

  get 'login' => "page#login"

  get 'dave/teach'

  get 'dave/speak'

  get 'dave/dig'

  get 'say/dave' => 'say#hello'
  get 'say/goodbye'
  get 'say/something'

   root 'page#home'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />

  <title>Daveblog</title>

  <%= stylesheet_link_tag    'application', media: 'screen', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag    'print', media: 'print', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <!--[if IE]><script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script><![endif]-->

</head>
<body>

<div id="wrapper"><!-- #wrapper -->

  <header><!-- header -->
    <h1><a href="#">Cowboy Up</a></h1>
    <h2>Where the buffalo roam</h2>

    <img alt="Rails" src="/assets/cowboyup.jpg" size= "940x200" />
    <!-- <img src="images/cowboyup.jpg" width="940" height="200" alt=""> --> <!-- header image -->
  </header><!-- end of header -->

  <nav><!-- top nav -->
    <div class="menu">
      <ul>
        <li>

            <%= nav_link_to "Home", "home", home_path, "current_page" %>

        </li>
        <li><%= nav_link_to "About Us", "about_us", about_us_path, "current_page" %>

          <ul>
            <li><%= link_to "Teach Dave", dave_teach_path %></li>
            <li><%= link_to "Contact Us", contact_us_path %></li>
            <li><a href="#">History</a></li>
            <li><a href="">Vision</a></li>
          </ul>
        </li>


        <li><%= nav_link_to "Articles", "articles", articles_path, "current_page" %>
          <ul>
            <li><%= link_to "Newsletter", newsletter_path %></li>
          </ul>
        </li>
        <li><%= nav_link_to "Calendar", "calendar", calendar_path, "current_page" %></li>

        <li><%= nav_link_to "Blog", "blog", blog_path, "current_page" %></li>
        <% if user_signed_in? %>
            <li><%= nav_link_to("Logout", "logout", destroy_user_session_path, "current_page") %></li>

        <% else %>
          <li><%= nav_link_to("Login", "login", new_user_session_path, "current_page") %></li>
        <% end %>
      </ul>
    </div>
  </nav><!-- end of top nav -->
  <% if user_signed_in? %>
      Welcome, <%= current_user.full_name %>
  <% end %>

  <section id="main"><!-- #main content and sidebar area -->
    <section id="container"><!-- #container -->
      <section id="content"><!-- #content -->


<%= yield %>


</section><!-- end of #content -->
</section><!-- end of #container -->

<aside id="sidebar"><!-- sidebar -->
  <h3>Things To Do</h3>
  <ul>
    <li><a href="#">Play Games</a></li>
    <li><a href="#">Chat With Friends</a></li>
    <li><a href="#">Swap Stories</a></li>
    <li><a href="#">Sell Stuff</a></li>
    <li><a href="#">Buy Stuff</a></li>
    <li><a href="#">Trade Stuff</a></li>
  </ul>

  <h3>Our Sponsors</h3>

  <img alt="advert" src="/assets/ad125.jpg" /><img alt="advert" src="/assets/ad125.jpg" /<br />
  <img alt="advert" src="/assets/ad125.jpg" /><img alt="advert" src="/assets/ad125.jpg" /<br /><br />
  <h3>Connect With Us</h3>
  <ul>
    <li><a href="#">Twitter</a></li>
    <li><a href="#">Facebook</a></li>
  </ul>

</aside><!-- end of sidebar -->

</section><!-- end of #main content and sidebar-->

<footer>
  <section id="footer-area">

    <section id="footer-outer-block">
      <aside id="first" class="footer-segment">
        <h3>Blogroll</h3>
        <ul>
          <li><a href="#">one linkylink</a></li>
          <li><a href="#">two linkylinks</a></li>
          <li><a href="#">three linkylinks</a></li>
          <li><a href="#">four linkylinks</a></li>
          <li><a href="#">five linkylinks</a></li>
        </ul>
      </aside><!-- end of #first footer segment -->

      <aside id="second" class="footer-segment">
        <h3>Awesome Stuff</h3>
        <ul>
          <li><a href="#">one linkylink</a></li>
          <li><a href="#">two linkylinks</a></li>
          <li><a href="#">three linkylinks</a></li>
          <li><a href="#">four linkylinks</a></li>
          <li><a href="#">five linkylinks</a></li>
        </ul>
      </aside><!-- end of #second footer segment -->

      <aside id="third" class="footer-segment">
        <h3>Coolness</h3>
        <ul>
          <li><a href="#">one linkylink</a></li>
          <li><a href="#">two linkylinks</a></li>
          <li><a href="#">three linkylinks</a></li>
          <li><a href="#">four linkylinks</a></li>
          <li><a href="#">five linkylinks</a></li>
        </ul>
      </aside><!-- end of #third footer segment -->

      <aside id="fourth" class="footer-segment">
        <h3>Blahdyblah</h3>
        <p>Integer nec odio. Praesent libero. Sed cursus ante dapibus diam. Sed nisi. Nulla quis sem at nibh elementum imperdiet. Duis sagittis ipsum.</p>
      </aside><!-- end of #fourth footer segment -->

    </section><!-- end of #footer-outer-block -->

  </section><!-- end of #footer-area -->
</footer>

</div><!-- #wrapper -->
<!-- Free template created by http://freehtml5templates.com -->

</body>
</html>